<?xml version="1.0" ?>
<!DOCTYPE core_timings [
  <!ELEMENT core_timings (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (node?,sequence?,count?,db_start?,db_end?,db_duration?,v_start?,v_end?,v_duration?)+>
  <!ELEMENT node (#PCDATA)>
  <!ELEMENT sequence (#PCDATA)>
  <!ELEMENT count (#PCDATA)>
  <!ELEMENT db_start (#PCDATA)>
  <!ELEMENT db_end (#PCDATA)>
  <!ELEMENT db_duration (#PCDATA)>
  <!ELEMENT v_start (#PCDATA)>
  <!ELEMENT v_end (#PCDATA)>
  <!ELEMENT v_duration (#PCDATA)>
]>
<core_timings>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,236</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:34:09</db_start>
    <db_end>2019-08-28 12:34:09</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:34:09</v_start>
    <v_end>2019-08-28 12:34:09</v_end>
    <v_duration>0.249</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,237</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:34:14</db_start>
    <db_end>2019-08-28 12:34:14</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:34:14</v_start>
    <v_end>2019-08-28 12:34:14</v_end>
    <v_duration>0.248</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,238</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:34:19</db_start>
    <db_end>2019-08-28 12:34:19</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:34:19</v_start>
    <v_end>2019-08-28 12:34:19</v_end>
    <v_duration>0.272</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,239</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:34:24</db_start>
    <db_end>2019-08-28 12:34:24</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:34:24</v_start>
    <v_end>2019-08-28 12:34:24</v_end>
    <v_duration>0.273</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,240</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:34:29</db_start>
    <db_end>2019-08-28 12:34:29</db_end>
    <db_duration>0.002</db_duration>
    <v_start>2019-08-28 12:34:29</v_start>
    <v_end>2019-08-28 12:34:29</v_end>
    <v_duration>0.249</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,241</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:34:34</db_start>
    <db_end>2019-08-28 12:34:34</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:34:34</v_start>
    <v_end>2019-08-28 12:34:34</v_end>
    <v_duration>0.25</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,242</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:34:39</db_start>
    <db_end>2019-08-28 12:34:39</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:34:39</v_start>
    <v_end>2019-08-28 12:34:39</v_end>
    <v_duration>0.25</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,243</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:34:44</db_start>
    <db_end>2019-08-28 12:34:44</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:34:44</v_start>
    <v_end>2019-08-28 12:34:44</v_end>
    <v_duration>0.25</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,244</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:34:49</db_start>
    <db_end>2019-08-28 12:34:49</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:34:49</v_start>
    <v_end>2019-08-28 12:34:49</v_end>
    <v_duration>0.247</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,245</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:34:54</db_start>
    <db_end>2019-08-28 12:34:54</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:34:54</v_start>
    <v_end>2019-08-28 12:34:54</v_end>
    <v_duration>0.248</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,246</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:34:59</db_start>
    <db_end>2019-08-28 12:34:59</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:34:59</v_start>
    <v_end>2019-08-28 12:34:59</v_end>
    <v_duration>0.247</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,247</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:35:04</db_start>
    <db_end>2019-08-28 12:35:04</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:35:04</v_start>
    <v_end>2019-08-28 12:35:04</v_end>
    <v_duration>0.247</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,248</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:35:09</db_start>
    <db_end>2019-08-28 12:35:09</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:35:09</v_start>
    <v_end>2019-08-28 12:35:09</v_end>
    <v_duration>0.25</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,249</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:35:14</db_start>
    <db_end>2019-08-28 12:35:14</db_end>
    <db_duration>0</db_duration>
    <v_start>2019-08-28 12:35:14</v_start>
    <v_end>2019-08-28 12:35:14</v_end>
    <v_duration>0.248</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,250</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:35:19</db_start>
    <db_end>2019-08-28 12:35:19</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:35:19</v_start>
    <v_end>2019-08-28 12:35:19</v_end>
    <v_duration>0.247</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,251</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:35:24</db_start>
    <db_end>2019-08-28 12:35:24</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:35:24</v_start>
    <v_end>2019-08-28 12:35:24</v_end>
    <v_duration>0.247</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,252</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:35:29</db_start>
    <db_end>2019-08-28 12:35:29</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:35:29</v_start>
    <v_end>2019-08-28 12:35:29</v_end>
    <v_duration>0.248</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,253</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:35:34</db_start>
    <db_end>2019-08-28 12:35:34</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:35:34</v_start>
    <v_end>2019-08-28 12:35:34</v_end>
    <v_duration>0.248</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,254</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:35:39</db_start>
    <db_end>2019-08-28 12:35:39</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:35:39</v_start>
    <v_end>2019-08-28 12:35:39</v_end>
    <v_duration>0.247</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,255</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:35:44</db_start>
    <db_end>2019-08-28 12:35:44</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:35:44</v_start>
    <v_end>2019-08-28 12:35:44</v_end>
    <v_duration>0.249</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,256</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:35:49</db_start>
    <db_end>2019-08-28 12:35:49</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:35:49</v_start>
    <v_end>2019-08-28 12:35:49</v_end>
    <v_duration>0.248</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,257</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:35:54</db_start>
    <db_end>2019-08-28 12:35:54</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:35:54</v_start>
    <v_end>2019-08-28 12:35:54</v_end>
    <v_duration>0.251</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,258</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:35:59</db_start>
    <db_end>2019-08-28 12:35:59</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:35:59</v_start>
    <v_end>2019-08-28 12:35:59</v_end>
    <v_duration>0.248</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,259</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:36:04</db_start>
    <db_end>2019-08-28 12:36:04</db_end>
    <db_duration>0</db_duration>
    <v_start>2019-08-28 12:36:04</v_start>
    <v_end>2019-08-28 12:36:04</v_end>
    <v_duration>0.265</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,260</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:36:09</db_start>
    <db_end>2019-08-28 12:36:09</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:36:09</v_start>
    <v_end>2019-08-28 12:36:09</v_end>
    <v_duration>0.247</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,261</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:36:14</db_start>
    <db_end>2019-08-28 12:36:14</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:36:14</v_start>
    <v_end>2019-08-28 12:36:14</v_end>
    <v_duration>0.248</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,262</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:36:19</db_start>
    <db_end>2019-08-28 12:36:19</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:36:19</v_start>
    <v_end>2019-08-28 12:36:19</v_end>
    <v_duration>0.25</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,263</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:36:24</db_start>
    <db_end>2019-08-28 12:36:24</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:36:24</v_start>
    <v_end>2019-08-28 12:36:24</v_end>
    <v_duration>0.251</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,264</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:36:29</db_start>
    <db_end>2019-08-28 12:36:29</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:36:29</v_start>
    <v_end>2019-08-28 12:36:29</v_end>
    <v_duration>0.274</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,265</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:36:34</db_start>
    <db_end>2019-08-28 12:36:34</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:36:34</v_start>
    <v_end>2019-08-28 12:36:34</v_end>
    <v_duration>0.252</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,266</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:36:39</db_start>
    <db_end>2019-08-28 12:36:39</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:36:39</v_start>
    <v_end>2019-08-28 12:36:39</v_end>
    <v_duration>0.248</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,267</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:36:44</db_start>
    <db_end>2019-08-28 12:36:44</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:36:44</v_start>
    <v_end>2019-08-28 12:36:44</v_end>
    <v_duration>0.249</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,268</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:36:49</db_start>
    <db_end>2019-08-28 12:36:49</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:36:49</v_start>
    <v_end>2019-08-28 12:36:49</v_end>
    <v_duration>0.249</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,269</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:36:54</db_start>
    <db_end>2019-08-28 12:36:54</db_end>
    <db_duration>0</db_duration>
    <v_start>2019-08-28 12:36:54</v_start>
    <v_end>2019-08-28 12:36:54</v_end>
    <v_duration>0.251</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,270</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:36:59</db_start>
    <db_end>2019-08-28 12:36:59</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:36:59</v_start>
    <v_end>2019-08-28 12:36:59</v_end>
    <v_duration>0.275</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,271</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:37:04</db_start>
    <db_end>2019-08-28 12:37:04</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:37:04</v_start>
    <v_end>2019-08-28 12:37:04</v_end>
    <v_duration>0.124</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,272</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:37:09</db_start>
    <db_end>2019-08-28 12:37:09</db_end>
    <db_duration>0.002</db_duration>
    <v_start>2019-08-28 12:37:09</v_start>
    <v_end>2019-08-28 12:37:09</v_end>
    <v_duration>0.125</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,273</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:37:14</db_start>
    <db_end>2019-08-28 12:37:14</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:37:14</v_start>
    <v_end>2019-08-28 12:37:14</v_end>
    <v_duration>0.125</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,274</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:37:19</db_start>
    <db_end>2019-08-28 12:37:19</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:37:19</v_start>
    <v_end>2019-08-28 12:37:19</v_end>
    <v_duration>0.124</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,275</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:37:24</db_start>
    <db_end>2019-08-28 12:37:24</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:37:24</v_start>
    <v_end>2019-08-28 12:37:24</v_end>
    <v_duration>0.123</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,276</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:37:29</db_start>
    <db_end>2019-08-28 12:37:29</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:37:29</v_start>
    <v_end>2019-08-28 12:37:29</v_end>
    <v_duration>0.126</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,277</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:37:34</db_start>
    <db_end>2019-08-28 12:37:34</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:37:34</v_start>
    <v_end>2019-08-28 12:37:34</v_end>
    <v_duration>0.124</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,278</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:37:39</db_start>
    <db_end>2019-08-28 12:37:39</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:37:39</v_start>
    <v_end>2019-08-28 12:37:39</v_end>
    <v_duration>0.124</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,279</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:37:44</db_start>
    <db_end>2019-08-28 12:37:44</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:37:44</v_start>
    <v_end>2019-08-28 12:37:44</v_end>
    <v_duration>0.127</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,280</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:37:49</db_start>
    <db_end>2019-08-28 12:37:49</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:37:49</v_start>
    <v_end>2019-08-28 12:37:49</v_end>
    <v_duration>0.124</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,281</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:37:54</db_start>
    <db_end>2019-08-28 12:37:54</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:37:54</v_start>
    <v_end>2019-08-28 12:37:54</v_end>
    <v_duration>0.146</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,282</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:37:59</db_start>
    <db_end>2019-08-28 12:37:59</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:37:59</v_start>
    <v_end>2019-08-28 12:37:59</v_end>
    <v_duration>0.147</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,283</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:38:04</db_start>
    <db_end>2019-08-28 12:38:04</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:38:04</v_start>
    <v_end>2019-08-28 12:38:04</v_end>
    <v_duration>0.146</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,284</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:38:09</db_start>
    <db_end>2019-08-28 12:38:09</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:38:09</v_start>
    <v_end>2019-08-28 12:38:09</v_end>
    <v_duration>0.148</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,285</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:38:14</db_start>
    <db_end>2019-08-28 12:38:14</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:38:14</v_start>
    <v_end>2019-08-28 12:38:14</v_end>
    <v_duration>0.147</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,286</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:38:19</db_start>
    <db_end>2019-08-28 12:38:19</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:38:19</v_start>
    <v_end>2019-08-28 12:38:19</v_end>
    <v_duration>0.146</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,287</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:38:24</db_start>
    <db_end>2019-08-28 12:38:24</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:38:24</v_start>
    <v_end>2019-08-28 12:38:24</v_end>
    <v_duration>0.146</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,288</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:38:29</db_start>
    <db_end>2019-08-28 12:38:29</db_end>
    <db_duration>0.002</db_duration>
    <v_start>2019-08-28 12:38:29</v_start>
    <v_end>2019-08-28 12:38:29</v_end>
    <v_duration>0.147</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,289</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:38:34</db_start>
    <db_end>2019-08-28 12:38:34</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:38:34</v_start>
    <v_end>2019-08-28 12:38:34</v_end>
    <v_duration>0.15</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,290</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:38:39</db_start>
    <db_end>2019-08-28 12:38:39</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:38:39</v_start>
    <v_end>2019-08-28 12:38:39</v_end>
    <v_duration>0.148</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,291</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:38:44</db_start>
    <db_end>2019-08-28 12:38:44</db_end>
    <db_duration>0.002</db_duration>
    <v_start>2019-08-28 12:38:44</v_start>
    <v_end>2019-08-28 12:38:44</v_end>
    <v_duration>0.148</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,292</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:38:49</db_start>
    <db_end>2019-08-28 12:38:49</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:38:49</v_start>
    <v_end>2019-08-28 12:38:49</v_end>
    <v_duration>0.171</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,293</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:38:54</db_start>
    <db_end>2019-08-28 12:38:54</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:38:54</v_start>
    <v_end>2019-08-28 12:38:54</v_end>
    <v_duration>0.172</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,294</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:38:59</db_start>
    <db_end>2019-08-28 12:38:59</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:38:59</v_start>
    <v_end>2019-08-28 12:38:59</v_end>
    <v_duration>0.17</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,295</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:39:04</db_start>
    <db_end>2019-08-28 12:39:04</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:39:04</v_start>
    <v_end>2019-08-28 12:39:04</v_end>
    <v_duration>0.171</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,296</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:39:09</db_start>
    <db_end>2019-08-28 12:39:09</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:39:09</v_start>
    <v_end>2019-08-28 12:39:09</v_end>
    <v_duration>0.197</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,297</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:39:14</db_start>
    <db_end>2019-08-28 12:39:14</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:39:14</v_start>
    <v_end>2019-08-28 12:39:14</v_end>
    <v_duration>0.169</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,298</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:39:19</db_start>
    <db_end>2019-08-28 12:39:19</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:39:19</v_start>
    <v_end>2019-08-28 12:39:19</v_end>
    <v_duration>0.17</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,299</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:39:24</db_start>
    <db_end>2019-08-28 12:39:24</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:39:24</v_start>
    <v_end>2019-08-28 12:39:24</v_end>
    <v_duration>0.197</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,300</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:39:29</db_start>
    <db_end>2019-08-28 12:39:29</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:39:29</v_start>
    <v_end>2019-08-28 12:39:29</v_end>
    <v_duration>0.198</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,301</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:39:34</db_start>
    <db_end>2019-08-28 12:39:34</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:39:34</v_start>
    <v_end>2019-08-28 12:39:34</v_end>
    <v_duration>0.198</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,302</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:39:39</db_start>
    <db_end>2019-08-28 12:39:39</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:39:39</v_start>
    <v_end>2019-08-28 12:39:39</v_end>
    <v_duration>0.197</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,303</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:39:44</db_start>
    <db_end>2019-08-28 12:39:44</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:39:44</v_start>
    <v_end>2019-08-28 12:39:44</v_end>
    <v_duration>0.172</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,304</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:39:49</db_start>
    <db_end>2019-08-28 12:39:49</db_end>
    <db_duration>0.002</db_duration>
    <v_start>2019-08-28 12:39:49</v_start>
    <v_end>2019-08-28 12:39:49</v_end>
    <v_duration>0.17</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,305</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:39:54</db_start>
    <db_end>2019-08-28 12:39:54</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:39:54</v_start>
    <v_end>2019-08-28 12:39:54</v_end>
    <v_duration>0.169</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,306</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:39:59</db_start>
    <db_end>2019-08-28 12:39:59</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:39:59</v_start>
    <v_end>2019-08-28 12:39:59</v_end>
    <v_duration>0.197</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,307</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:40:04</db_start>
    <db_end>2019-08-28 12:40:04</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:40:04</v_start>
    <v_end>2019-08-28 12:40:04</v_end>
    <v_duration>0.169</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,308</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:40:09</db_start>
    <db_end>2019-08-28 12:40:09</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:40:09</v_start>
    <v_end>2019-08-28 12:40:09</v_end>
    <v_duration>0.195</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,309</sequence>
    <count>0</count>
    <db_start>2019-08-28 12:40:14</db_start>
    <db_end>2019-08-28 12:40:14</db_end>
    <db_duration>0.001</db_duration>
    <v_start>2019-08-28 12:40:14</v_start>
    <v_end>2019-08-28 12:40:14</v_end>
    <v_duration>0.171</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,310</sequence>
    <count>1</count>
    <db_start>2019-08-28 12:40:19</db_start>
    <db_end>2019-08-28 12:40:19</db_end>
    <db_duration>0.027</db_duration>
    <v_start>2019-08-28 12:40:19</v_start>
    <v_end>2019-08-28 12:40:19</v_end>
    <v_duration>0.184</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,311</sequence>
    <count>1</count>
    <db_start>2019-08-28 12:40:24</db_start>
    <db_end>2019-08-28 12:40:24</db_end>
    <db_duration>0.026</db_duration>
    <v_start>2019-08-28 12:40:24</v_start>
    <v_end>2019-08-28 12:40:24</v_end>
    <v_duration>0.18</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,312</sequence>
    <count>1</count>
    <db_start>2019-08-28 12:40:29</db_start>
    <db_end>2019-08-28 12:40:29</db_end>
    <db_duration>0.026</db_duration>
    <v_start>2019-08-28 12:40:29</v_start>
    <v_end>2019-08-28 12:40:29</v_end>
    <v_duration>0.181</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,313</sequence>
    <count>1</count>
    <db_start>2019-08-28 12:40:34</db_start>
    <db_end>2019-08-28 12:40:34</db_end>
    <db_duration>0.026</db_duration>
    <v_start>2019-08-28 12:40:34</v_start>
    <v_end>2019-08-28 12:40:34</v_end>
    <v_duration>0.208</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,314</sequence>
    <count>1</count>
    <db_start>2019-08-28 12:40:39</db_start>
    <db_end>2019-08-28 12:40:39</db_end>
    <db_duration>0.024</db_duration>
    <v_start>2019-08-28 12:40:39</v_start>
    <v_end>2019-08-28 12:40:39</v_end>
    <v_duration>0.181</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,315</sequence>
    <count>1</count>
    <db_start>2019-08-28 12:40:44</db_start>
    <db_end>2019-08-28 12:40:44</db_end>
    <db_duration>0.026</db_duration>
    <v_start>2019-08-28 12:40:44</v_start>
    <v_end>2019-08-28 12:40:44</v_end>
    <v_duration>0.18</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,316</sequence>
    <count>1</count>
    <db_start>2019-08-28 12:40:49</db_start>
    <db_end>2019-08-28 12:40:49</db_end>
    <db_duration>0.027</db_duration>
    <v_start>2019-08-28 12:40:49</v_start>
    <v_end>2019-08-28 12:40:49</v_end>
    <v_duration>0.245</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,317</sequence>
    <count>1</count>
    <db_start>2019-08-28 12:40:54</db_start>
    <db_end>2019-08-28 12:40:54</db_end>
    <db_duration>0.026</db_duration>
    <v_start>2019-08-28 12:40:54</v_start>
    <v_end>2019-08-28 12:40:54</v_end>
    <v_duration>0.179</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,318</sequence>
    <count>1</count>
    <db_start>2019-08-28 12:40:59</db_start>
    <db_end>2019-08-28 12:40:59</db_end>
    <db_duration>0.025</db_duration>
    <v_start>2019-08-28 12:40:59</v_start>
    <v_end>2019-08-28 12:40:59</v_end>
    <v_duration>0.203</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,319</sequence>
    <count>1</count>
    <db_start>2019-08-28 12:41:04</db_start>
    <db_end>2019-08-28 12:41:04</db_end>
    <db_duration>0.026</db_duration>
    <v_start>2019-08-28 12:41:04</v_start>
    <v_end>2019-08-28 12:41:04</v_end>
    <v_duration>0.18</v_duration>
  </DATA_RECORD>
  <DATA_RECORD>
    <node>GCI7I</node>
    <sequence>2,320</sequence>
    <count>1</count>
    <db_start>2019-08-28 12:41:09</db_start>
    <db_end>2019-08-28 12:41:09</db_end>
    <db_duration>0.008</db_duration>
    <v_start>2019-08-28 12:41:09</v_start>